### ISSUE TITLE
Python 2 vs 3

### ISSUE THREAD

**Issue by a466990-PDarbonne** [automicus/PyISY#23] opened 2017-01-08 14:33 UTC
Hello,

Maybe not an issue but thought I would mention.  Your code (great by the way!) v1.07 available via pip will not work properly on Python 2.7.9 - generates a traceback when executed.  The v1.0.7 **does** work properly on Python 3.4.2.  

The earlier release available on your site v1.0.5 does work properly on both Python v2.7.9 and Python 3.4.2.  

As I mentioned - perhaps intentional but after searching for a while I hadn't seen anyone else providing this feedback so thought I would.

**Comment by jimboca** [comment] 2017-01-08 16:11
I run the latest version from github on 2.7 with no issues, so it must be related to some devices you have or has been fixed since that release. If you post the traceback I can take a look, or download the latest from github.

**Comment by pdarbonne** [comment] 2017-01-08 17:08
Thanks for the reply.  You may be correct that the issue is on my end.  See the below test I ran and then used pip to update to v1.0.7.  Also - I am running on a raspberry pi.  

pi@raspberrypi1:~/Progs $ python ISY-TestPi.py 

Connection to ISY is: True

PyISY                     - Python module to talk to ISY994 from UDI.
  INSTALLED: **1.0.5**
  LATEST:    1.0.7

**use pip to upgrade to the latest release**
pi@raspberrypi1:~/Progs $ sudo pip install PyISY --upgrade
Downloading/unpacking PyISY from https://pypi.python.org/packages/b3/12/661fbb7d511209d9cc2a777829a20f515b4323ce2177bb4d2f24eb5cfa66/PyISY-1.0.7.tar.gz#md5=170360d6e835ed41287e23f7f032e428
  Downloading PyISY-1.0.7.tar.gz
  Running setup.py (path:/tmp/pip-build-q3Xbdy/PyISY/setup.py) egg_info for package PyISY
    
Downloading/unpacking requests from https://pypi.python.org/packages/ed/9e/60cc074968c095f728f0d8d28370e8d396fa60afb7582735563cccf223dd/requests-2.12.4-py2.py3-none-any.whl#md5=3989eaeaa2ccad20470afc61710d3498 (from PyISY)
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB): 576kB downloaded
Requirement already up-to-date: VarEvents in /usr/local/lib/python2.7/dist-packages (from PyISY)
Installing collected packages: PyISY, requests
  Found existing installation: PyISY 1.0.5
    Uninstalling PyISY:
      Successfully uninstalled PyISY
  Running setup.py install for PyISY
    
  Found existing installation: requests 2.4.3
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed PyISY requests
Cleaning up...

**Below is the run using v1.0.7 and the resulting Traceback**  

pi@raspberrypi1:~/Progs $ python ISY-TestPi.py 
Traceback (most recent call last):
  File "ISY-TestPi.py", line 17, in <module>
    isy = PyISY.ISY(ADDR, PORT, USER, PASS)
  File "/usr/local/lib/python2.7/dist-packages/PyISY/ISY.py", line 84, in __init__
    self.nodes = Nodes(self, xml=self.conn.getNodes())
  File "/usr/local/lib/python2.7/dist-packages/PyISY/Nodes/__init__.py", line 73, in __init__
    self.parse(xml)
  File "/usr/local/lib/python2.7/dist-packages/PyISY/Nodes/__init__.py", line 211, in parse
    if 'uom' in nprop[0].attributes:
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 522, in __getitem__
    return self._attrs[attname_or_tuple]
KeyError: 0

**Comment by rmkraus** [comment] 2017-01-08 17:16
Thanks for the feedback. This was fixed in issue #17 and PR #20. The next time I push to PyPI, you should be able to run on Python 2.7 again. You could also pull from directly from Github to start using it now. I'm not 100% sure when I'll push to PyPI next, I've got some other projects I'm working on and then I have to make it back around to the PR's that are here.

**Closed** 2020-09-08 08:09 UTC
